//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiagallery.FoodSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodRegistrations
    {
        public int Id { get; set; }
        public int FoodCensusId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> FoodStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Appertizer { get; set; }
        public bool Food { get; set; }
        public bool FoodWithoutRice { get; set; }
        public int CreateUserId { get; set; }
        public int ModifyUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Ip { get; set; }
    
        public virtual FoodCensus FoodCensus { get; set; }
    }
}
