//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiagallery.FoodSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCensus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodCensus()
        {
            this.FoodRegistrations = new HashSet<FoodRegistrations>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FoodName { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Holiday { get; set; }
        public bool TypeFood { get; set; }
        public int CreateUserId { get; set; }
        public int ModifyUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Ip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodRegistrations> FoodRegistrations { get; set; }
    }
}
