//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiaGallery.BotDailyReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyReport()
        {
            this.DailyReportBank = new HashSet<DailyReportBank>();
            this.DailyReportCurrency = new HashSet<DailyReportCurrency>();
            this.DailyReportLog = new HashSet<DailyReportLog>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public int BranchCalendarId { get; set; }
        public int Status { get; set; }
        public int NumberSaleFactor { get; set; }
        public decimal SaleWeight { get; set; }
        public decimal SaleWeightPercent { get; set; }
        public long SaleEntry { get; set; }
        public long SaleExit { get; set; }
        public int NumberReturnedFactor { get; set; }
        public decimal ReturnedWeight { get; set; }
        public decimal ReturnWeightPercent { get; set; }
        public long ReturnedEntry { get; set; }
        public long ReturnedExit { get; set; }
        public long OtherCash { get; set; }
        public long CashEntry { get; set; }
        public long CashExit { get; set; }
        public string OtherCurrency { get; set; }
        public decimal OtherCurrencyValue { get; set; }
        public long OtherCurrencyRialValue { get; set; }
        public long OtherCurrencyRialEntry { get; set; }
        public long OtherCurrencyRialExit { get; set; }
        public long InventoryCash { get; set; }
        public decimal GoldDeficitWeight { get; set; }
        public long GoldDeficitEntry { get; set; }
        public long GoldDeficitExit { get; set; }
        public int GiftNumberEntry { get; set; }
        public int GiftNumberExit { get; set; }
        public long GiftEntry { get; set; }
        public long GiftExit { get; set; }
        public int CheckNumber { get; set; }
        public long CheckEntry { get; set; }
        public long CheckExit { get; set; }
        public string LeatherStoneDescriptionEntry { get; set; }
        public string LeatherStoneDescriptionExit { get; set; }
        public long LeatherStoneEntry { get; set; }
        public long LeatherStoneExit { get; set; }
        public int CoinNumber { get; set; }
        public string CoinDescription { get; set; }
        public long CoinEntry { get; set; }
        public long CoinExit { get; set; }
        public decimal OtherKiaGoldWeight { get; set; }
        public long OtherKiaGoldEntry { get; set; }
        public long OtherKiaGoldExit { get; set; }
        public decimal OtherGoldWeight { get; set; }
        public long OtherGoldEntry { get; set; }
        public long OtherGoldExit { get; set; }
        public long CreditorCustomerEntry { get; set; }
        public long CreditorCustomerExit { get; set; }
        public long DebtorCustomerEntry { get; set; }
        public long DebtorCustomerExit { get; set; }
        public int DepositBeforeCount { get; set; }
        public long DepositBeforeEntry { get; set; }
        public long DepositBeforeExit { get; set; }
        public int DepositNewCount { get; set; }
        public long DepositNewEntry { get; set; }
        public long DepositNewExit { get; set; }
        public long DiscountEntry { get; set; }
        public long DiscountExit { get; set; }
        public long CostCourierPostEntry { get; set; }
        public long CostCourierPostExit { get; set; }
        public long CostEntry { get; set; }
        public long CostExit { get; set; }
        public string Description { get; set; }
        public bool Sent { get; set; }
        public long LoyalityEntry { get; set; }
        public long LoyalityExit { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual BranchCalendar BranchCalendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyReportBank> DailyReportBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyReportCurrency> DailyReportCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyReportLog> DailyReportLog { get; set; }
    }
}
