//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiaGallery.BotDailyReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReportCurrency
    {
        public int Id { get; set; }
        public int DailyReportId { get; set; }
        public int CurrencyId { get; set; }
        public decimal Value { get; set; }
        public long RialValue { get; set; }
        public long RialEntry { get; set; }
        public long RialExit { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual DailyReport DailyReport { get; set; }
    }
}
