//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiaGallery.BotDailyReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReportBank
    {
        public int Id { get; set; }
        public int DailyReportId { get; set; }
        public int BankId { get; set; }
        public long Entry { get; set; }
        public long Exit { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual DailyReport DailyReport { get; set; }
    }
}
