//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiaGallery.BotDailyReport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReportLog
    {
        public int Id { get; set; }
        public int DailyReportId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public string PrevData { get; set; }
        public string Ip { get; set; }
    
        public virtual DailyReport DailyReport { get; set; }
    }
}
