//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiaGallery.BotDailyReport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiaGalleryMainEntities : DbContext
    {
        public KiaGalleryMainEntities()
            : base("name=KiaGalleryMainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppToken> AppToken { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BranchCalendar> BranchCalendar { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DailyReportBank> DailyReportBank { get; set; }
        public virtual DbSet<DailyReportLog> DailyReportLog { get; set; }
        public virtual DbSet<DailyReportMessage> DailyReportMessage { get; set; }
        public virtual DbSet<DailyReportSettings> DailyReportSettings { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<BotDailyReportUserData> BotDailyReportUserData { get; set; }
        public virtual DbSet<DailyReportCurrency> DailyReportCurrency { get; set; }
        public virtual DbSet<BranchGolds> BranchGolds { get; set; }
        public virtual DbSet<DailyReport> DailyReport { get; set; }
    }
}
