//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branches()
        {
            this.UserProfile2 = new HashSet<UserProfile>();
            this.People = new HashSet<People>();
        }
    
        public int Id { get; set; }
        public int CityId { get; set; }
        public int BranchType { get; set; }
        public int OrderNo { get; set; }
        public int WorkingHour { get; set; }
        public string OwnerName { get; set; }
        public string OwnerNationalityCode { get; set; }
        public string OwnerNationalityNo { get; set; }
        public string OwnerFatherName { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Address { get; set; }
        public string EnglishAddress { get; set; }
        public string Color { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CreditCard { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool Active { get; set; }
        public float GoldDebt { get; set; }
        public long RialDebt { get; set; }
        public float GoldCredit { get; set; }
        public int CreateUserId { get; set; }
        public int ModifyUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Ip { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<People> People { get; set; }
    }
}
