//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int Id { get; set; }
        public int PersonNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ShortName { get; set; }
        public string NikName { get; set; }
        public string FatherName { get; set; }
        public bool Gender { get; set; }
        public string NationalCode { get; set; }
        public string BirthCertificateNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string NecessaryNumber { get; set; }
        public string ExportFrom { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public bool Supervisor { get; set; }
        public int ContractSubject { get; set; }
        public string PromissoryNoteNumber { get; set; }
        public Nullable<int> JobId { get; set; }
        public bool Married { get; set; }
        public Nullable<int> Children { get; set; }
        public bool Contract { get; set; }
        public int ContractInMonth { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public bool Insurance { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> InsuranceExpireDate { get; set; }
        public Nullable<System.DateTime> InsuranceBeginDate { get; set; }
        public int Education { get; set; }
        public Nullable<long> Reward { get; set; }
        public Nullable<long> ActivityAmount { get; set; }
        public Nullable<long> SupervisorSalary { get; set; }
        public bool Active { get; set; }
        public string Major { get; set; }
        public string MajorCurrent { get; set; }
        public bool EducationalStatus { get; set; }
        public int PersonType { get; set; }
        public Nullable<decimal> ShiftActivity { get; set; }
        public int CreateUserId { get; set; }
        public int ModifyUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Ip { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
