//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string DestinationNumber { get; set; }
        public string DayOfMonth { get; set; }
        public string DayOfWeek { get; set; }
        public int SendingTimeMethod { get; set; }
        public string UserId { get; set; }
        public string BranchId { get; set; }
        public int CreateUserId { get; set; }
        public int ModifyUserId { get; set; }
        public System.DateTime SendingDate { get; set; }
        public string Time { get; set; }
        public int TimeTotalMinutes { get; set; }
        public bool Sent { get; set; }
        public string Ip { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
